name: Cypress Tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          component: true
          browser: chrome

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
